import { StyleSheet } from 'react-native';

export const createCalendarStyles = StyleSheet.create({
  modalContainer: {
    flex: 1,
    backgroundColor: '#f8f9fa',  // Light background color for a fresh feel
    padding: 20,
  },
  topBar: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    marginBottom: 20,
  },
  modalContent: {
    marginBottom: 20,
  },
  label: {
    marginBottom: 8,
    fontSize: 18,
    fontWeight: '600',
    color: '#333',
  },
  input: {
    height: 50,
    borderColor: '#ccc',
    borderWidth: 1,
    marginBottom: 15,
    paddingLeft: 15,
    paddingRight: 15,
    borderRadius: 15,
    backgroundColor: '#fff',
    fontSize: 16,
    fontWeight: '400',
  },
  textArea: {
    height: 120,
    textAlignVertical: 'top',
    borderColor: '#ccc',
    borderWidth: 1,
    borderRadius: 15,
    padding: 10,
    backgroundColor: '#fff',
    fontSize: 16,
  },
  fixedButtonContainer: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: '#fff',
    paddingBottom: 25,
    alignItems: 'center',
    paddingHorizontal: 20,
    borderTopWidth: 1,
    borderTopColor: '#e0e0e0',
  },
  fixedActionButton: {
    backgroundColor: '#5c6bc0',  // Soft blue for the action button
    padding: 15,
    borderRadius: 25,
    width: '70%',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 10,
    elevation: 5,
  },
  buttonText: {
    color: '#fff',
    fontSize: 18,
    fontWeight: 'bold',
  },
  scrollViewContainer: {
    flex: 1,
    paddingBottom: 90,
  },
  imagePreview: {
    width: 120,
    height: 120,
    borderRadius: 10,
    marginTop: 10,
    borderWidth: 2,
    borderColor: '#e0e0e0',
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 5,
    elevation: 3,
  },
  imagePlaceholder: {
    color: '#aaa',
    fontSize: 16,
    textAlign: 'center',
    marginTop: 10,
  },
  imagePickerArea: {
    width: '100%',
    height: 120,
    backgroundColor: '#e0e0e0', // Gray background when no image is selected
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 10,
    borderWidth: 2,
    borderColor: '#e0e0e0',
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 5,
    elevation: 3,
  },
  imagePreview: {
    width: '100%',
    height: 120,
    borderRadius: 10,
    marginTop: 10,
    borderWidth: 2,
    borderColor: '#e0e0e0',
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 5,
    elevation: 3,
  },  
});